version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/app
    command: yarn run dev

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${DEFAULT_DB}
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - pg-admin-data:/var/lib/pgadmin

volumes:
  data:
  pg-admin-data:
