version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "9000:9000"
    command: yarn start

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
      - PGADMIN_LISTEN_PORT=
    ports:
      - 
    volumes:
      - pg-admin-data:

volumes:
  data:
  pg-admin-data:
