export const ACTION = {
    "a1":{
            "Id":1,
            "Action":"ViewProfile",
            "Function":"current_user"
        },
    "a2":{
            "Id":2,
            "Action":"ViewUserList",
            "Function":"get_all"
        },
    "a3":{
            "Id":3,
            "Action":"ViewUserDetails",
            "Function":"get"
        },
    "a4":{
            "Id":4,
            "Action":"CreateUser",
            "Function":"create"
        },
    "a5":{
            "Id":5,
            "Action":"RemoveUser",
            "Function":"remove"
        },
    "a6":{
            "Id":6,
            "Action":"UpdateUser",
            "Function":"update"
        },
    "a7":{
            "Id":7,
            "Action":"ChangePassword",
            "Function":"change_pass"
        },
    "a8":{
            "Id":8,
            "Action":"ViewAccesRightList",
            "Function":"get_all"
        },
    "a9":{
            "Id":9,
            "Action":"ViewAccessRightDetails",
            "Function":"get"
        },
    "a10":{
            "Id":10,
            "Action":"CreateAccessRight",
            "Function":"create"
        },
    "a11":{
            "Id":11,
            "Action":"RemoveAccessRight",
            "Function":"remove"
        },
    "a12":{
            "Id":12,
            "Action":"RemoveMultipleAccessRight",
            "Function":"remove_multiple"
        },

    "a13":{
            "Id":13,
            "Action":"UpdateAccessRight",
            "Function":"update"
        },
    "a14":{
            "Id":14,
            "Action":"",
            "Function":""
        },
    "a15":{
            "Id":15,
            "Action":"",
            "Function":""
        },
    "a16":{
            "Id":16,
            "Action":"",
            "Function":""
        },
    "a17":{
            "Id":17,
            "Action":"",
            "Function":""
        },
    "a18":{
            "Id":18,
            "Action":"",
            "Function":""
        },
    "a19":{
            "Id":19,
            "Action":"",
            "Function":""
        },
    "a20":{
            "Id":20,
            "Action":"",
            "Function":""
        },
    "a21":{
            "Id":21,
            "Action":"",
            "Function":""
        },
    "a22":{
            "Id":22,
            "Action":"",
            "Function":""
        },
    "a23":{
            "Id":23,
            "Action":"",
            "Function":""
        },
    "a24":{
            "Id":24,
            "Action":"",
            "Function":""
        },
    "a25":{
            "Id":25,
            "Action":"",
            "Function":""
        },
    "a26":{
            "Id":26,
            "Action":"",
            "Function":""
        },
    "a27":{
            "Id":27,
            "Action":"",
            "Function":""
        },
    "a28":{
            "Id":28,
            "Action":"",
            "Function":""
        },
    "a29":{
            "Id":29,
            "Action":"",
            "Function":""
        },
    "a30":{
            "Id":30,
            "Action":"",
            "Function":""
        },
    "31":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "32":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "33":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "34":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "35":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "36":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "37":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "38":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "39":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "40":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "41":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "42":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "43":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "44":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "45":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "46":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "47":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "48":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "49":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "50":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "51":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "52":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "53":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "54":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "55":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "56":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "57":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "58":{
            "Id":"",
            "Action":"",
            "Function":""
        },
}