export const user_action = {
    "a1":{
            "Id":1,
            "Action":"ViewProfile",
            "Function":"current_user"
        },
    "a2":{
            "Id":2,
            "Action":"ViewUserList",
            "Function":"get_all"
        },
    "a3":{
            "Id":3,
            "Action":"ViewUserDetails",
            "Function":"get"
        },
    "a4":{
            "Id":4,
            "Action":"CreateUser",
            "Function":"create"
        },
    "a5":{
            "Id":5,
            "Action":"RemoveUser",
            "Function":"remove"
        },
    "a6":{
            "Id":6,
            "Action":"UpdateUser",
            "Function":"update"
        },
    "a7":{
            "Id":7,
            "Action":"ChangePassword",
            "Function":"change_pass"
        },
    "a8":{
            "Id":8,
            "Action":"",
            "Function":""
        },
    "a9":{
            "Id":9,
            "Action":"",
            "Function":""
        },
    "a10":{
            "Id":10,
            "Action":"",
            "Function":""
        },
    "11":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "12":{
            "Id":"",
            "Action":"",
            "Function":""
        },

    "13":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "14":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "15":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "16":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "17":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "18":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "19":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "20":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "21":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "22":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "23":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "24":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "25":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "26":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "27":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "28":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "29":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "30":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "31":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "32":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "33":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "34":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "35":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "36":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "37":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "38":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "39":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "40":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "41":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "42":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "43":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "44":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "45":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "46":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "47":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "48":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "49":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "50":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "51":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "52":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "53":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "54":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "55":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "56":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "57":{
            "Id":"",
            "Action":"",
            "Function":""
        },
    "58":{
            "Id":"",
            "Action":"",
            "Function":""
        },
}